### ISSUE TITLE
Tree item color doesn't update on theme change (FLTK 1.3.5)

### ISSUE THREAD

**Issue by fire-eggs** [gnuwimp/flw#1]
Greatly impressed! I'm liking a lot of what I see here ...

I did note that in `test_theme`, the tree color doesn't update as the theme changes. Black text in a dark theme does not work. You can see it in your screen cap as well. 

I don't know why this is so, I'd have thought FLTK would deal with it automagically. 

I made this change in `test_theme` to "fix" it:
```
    void make_tree() {
        tree->clear();
        tree->item_labelfgcolor(FL_FOREGROUND_COLOR);
```

I'm testing with FLTK 1.3.5 right now, I don't know yet if this is also an issue with FLTK 1.4.

**Comment by gnuwimp** [comment]
That's an issue with the tree widget not using FL_FOREGROUND_COLOR.
